# Set True color
set-option -sa terminal-overrides ",xterm*:Tc"

# Status bar on top
set -g status-position bottom

# Set mouse 
set -g mouse on

# Set prefix key
unbind C-b
set-option -g prefix C-Space
bind C-Space send-prefix

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Shift arrow to switch windows
bind -n S-Left  previous-window
bind -n S-Right next-window

# Tmux plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'

# Status Bar
set-option -g status-bg "#1A1A1A"              
set-option -g status-fg "#F8F8F2"              
set-option -g status-position bottom           
set-option -g status-right "#[fg=#AB9DF2]%Y-%m-%d #[fg=#AB9DF2]%H:%M"
set-option -g status-left "#[fg=#FC9867] #S #[fg=#F8F8F2]"
set-option -g window-status-current-style bg=#78DCE8,fg=#2D2A2E,bold
set-option -g window-status-current-format "#[bg=#AB9DF2,fg=#2D2A2E,bold] #I: #W #[default]"
set-option -g window-status-style bg=#2D2A2E,fg=#F8F8F2               
set-option -g window-status-format "#[fg=#F8F8F2] #I: #W #[default]"
set-option -g message-style bg=#1A1A1A,fg=#AB9DF2           

# Visual mode colors
set-option -g mode-style "bg=#333333,fg=#F8F8F2"  # Slightly dark background with light text

# Set vi-mode and copy mode configs
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Create new windows at the current path
bind c new-window -c "#{pane_current_path}"

# Initialize TMUX plugin manager
run '~/.tmux/plugins/tpm/tpm'
